Repository arpit456jain/Amazing-Css-Effects, pull requests merged in 2021-07, with the labels that each got.

#23 welcome-bot added
  .github/config.yml
  README.md
Labels: good first issue

#33 logo added in index.html
  index.html
  style.css
Labels: enhancement, good first issue

#52 Deepanjali Vyas
  demo/index.html
  demo/style/style.css
Labels: level 2

#53 Nitesh Rawat
  Nitesh Rawat/index.html
  Nitesh Rawat/styles.css
  Nitesh Rawat/user.jpg
Labels: level 3

#67 Shruti Singh
  Weild the web - Shortcut.lnk
  Weild the web/avatar.png
  Weild the web/index.html
  Weild the web/pic.jpg
  Weild the web/style.css
Labels: level 2

#72 github pages website added to readme
  README.md
Labels: DCP21, level1

#74 Neuromorphic Calculator added
  Neuromorphic Calculator/index.html
  Neuromorphic Calculator/style.css
Labels: DCP21, level2

#76 Vertical Own Project Timeline With CSS and a Touch of JavaScript
  Project Timeline View/index.html
  Project Timeline View/script.js
  Project Timeline View/style.css
Labels: level2

#82 Added Neumorphic Login form
  Neumorphic_Login_Form/index.html
  Neumorphic_Login_Form/style.css
Labels: level2

#83 Ripple Loader Animation Effect
  Ripple Loader Animation/index.html
  Ripple Loader Animation/style.css
Labels: DCP21, level3

#84 Added navbar bubble animation
  Bubble-Navbar-Animation/index.html
  Bubble-Navbar-Animation/script.js
  Bubble-Navbar-Animation/style.css
  style_links.json
Labels: DCP21, level2

#87 Water waves footer
  Water Wavy Footer/ss1.PNG
  Water Wavy Footer/ss2.PNG
  Water Wavy Footer/wave.svg
  Water Wavy Footer/waves_footer.css
  Water Wavy Footer/waves_footer.html
Labels: DCP21, level2

#90 Rc2208 steaming cup
  Steaming cup/Tea cup.html
Labels: DCP21, Level2

#95 Glowing checkboxes
  Glowing checkboxes/glowing.css
  Glowing checkboxes/glowing_checkboxes.html
  Glowing checkboxes/ss1.PNG
  Glowing checkboxes/ss2.PNG
Labels: DCP21, Level2

#93 Credit Card UI Design
  Credit Card UI/index.html
  Credit Card UI/style.css
Labels: DCP21, Level2

#99 Rain Effect
  Rain Effect/Rain Effect.html
  Rain Effect/rain.png
Labels: DCP21, Level2

#101 Updates to style_links.json .
  smoke effect/index.html
  style_links.json
Labels: DCP21, Level2

#100 added animated gradient
  Animated Gradient using Pure CSS/index.html
  Animated Gradient using Pure CSS/main.css
  style_links.json
Labels: DCP21, Level1

#104 Added Horizontal Card Hover
  Horizontal hover effect/card.css
  Horizontal hover effect/card.html
  Horizontal hover effect/img/image.jpg
Labels: DCP21, Level2

#107 Made Horizontal Card transition Responsive
  Horizontal hover effect/card.css
Labels: DCP21, Level2

#108 added parallax effect
  parallax effect/img/image1.jpg
  parallax effect/img/image2.jpg
  parallax effect/img/image3.jpg
  parallax effect/index.html
  parallax effect/main.css
  style_links.json
Labels: DCP21, Level2

#110 Water Drop Effect added
  Water Drop Effect/index.html
  Water Drop Effect/style.css
Labels: DCP21, Level2

#117 Ripple button effect
  Ripple Button Effect/ripple_button_effect.css
  Ripple Button Effect/ripple_button_effect.html
Labels: DCP21, Level2

#111 added rotatingcards
  Rotating cards/index.html
  Rotating cards/style.css
Labels: DCP21, Level2

#123 Added the code for Loader in HTML and CSS
  Loader/index.html
  Loader/style.css
Labels: DCP21, Level2

#124 Added the code for Hidden Search Bar
  Hidden_Search_Bar/index.html
  Hidden_Search_Bar/script.js
  Hidden_Search_Bar/style.css
Labels: DCP21, Level2

#119 Blur depth effect
  Depth Effect with bg blur/Devincept.gif
  Depth Effect with bg blur/depth_effect.css
  Depth Effect with bg blur/depth_effect.html
Labels: DCP21, Level2

#126 Added the Code for Camera Design
  Camera_Design/img1.jpg
  Camera_Design/index.html
  Camera_Design/script.js
  Camera_Design/style.css
Labels: DCP21, Level3

#121 Glowing gradient loader
  css glowing gradient loader ring/index.html
  css glowing gradient loader ring/style.css
Labels: DCP21, Level2

#129 corrected the issue template
  .github/ISSUE_TEMPLATE/Bug_Feature_Docs.md
Labels: DCP21, Level0

#130 Starry background
  Parallax star/star.html
  Parallax star/style.css
Labels: DCP21, Level3

#132 Add contentonhover
  Content on Hover/index.html
  Content on Hover/style.css
Labels: DCP21, Level2

#134 FAQ Accordion
  FAQ Accordion/index.html
  FAQ Accordion/style.css
  style_links.json
Labels: DCP21, Level2

#136 Patch 4
  3D Animation Button/index.html
  3D Animation Button/style.css
Labels: DCP21, Level2

#137 Added GlassMorphic Sign Up page
  GlassMorphic-SignUpForm/index.html
  GlassMorphic-SignUpForm/style.css
Labels: DCP21, Level2

#138 Added Periodic Table
  Periodic Table/Periodic Table SS.png
  Periodic Table/index.html
  Periodic Table/style.css
  style_links.json
Labels: DCP21, Level2

#139 Video Preview Button
  Video-preview-button--Main/README.md
  Video-preview-button--Main/index.html
  Video-preview-button--Main/style.css
Labels: DCP21, Level2

#142 Added the code for Responsive Box Hover Effect
  Responsive Box Hover Effect/images/aws.png
  Responsive Box Hover Effect/images/cpp.png
  Responsive Box Hover Effect/images/css.png
  Responsive Box Hover Effect/images/docker.png
  Responsive Box Hover Effect/images/java.png
  Responsive Box Hover Effect/images/js.png
  Responsive Box Hover Effect/images/python.png
  Responsive Box Hover Effect/images/react.png
  Responsive Box Hover Effect/index.html
  Responsive Box Hover Effect/style.css
Labels: DCP21, Level2

#151 Update Home Page UI
  3d flip hover effect/preview.png
  Animated Login Fom/preview.png
  Card Hover Effect/preview.png
  Credit Card UI/preview.png
  Glowing Gradient Border/preview.png
  Glowing checkboxes/preview.png
  Glowing loading page animation/preview.png
  Neon Buttons/preview.png
  Neumorphic_Login_Form/preview.png
  index.html
  script.js
  style.css
Labels: DCP21, Level3

#155 Added back to top
  index.html
  script.js
  style.css
Labels: DCP21, Level1

#154 added preview images
  3D Animation Button/preview.png
  Animated Gradient using Pure CSS/preview.png
  Bubble-Navbar-Animation/preview.png
  Camera_Design/preview.png
  Changing Typing Effects/preview.png
  Content on Hover/preview.png
  Depth Effect with bg blur/preview.png
  FAQ Accordion/preview.png
  GlassMorphic-SignUpForm/preview.png
  Hidden_Search_Bar/preview.png
  Horizontal hover effect/preview.png
  LED Loading Effect/preview.png
  Loader/preview.png
  Loading Animation/preview.png
  Nitesh Rawat/preview.png
  Periodic Table/preview.png
  PreLoad Animation/preview.png
  Price Cards/preview-pricecard1.png
  Price Cards/preview-pricecard2.png
  Profile-card/preview.png
  Project Timeline View/preview.png
  Rain Effect/preview.png
  Rainbow Strip Button/preview.png
  Responsive Box Hover Effect/preview.png
  Ripple Button Effect/preview.png
  Ripple Loader Animation/preview.png
  Rotating cards/preview.png
  Sass-Buttons/preview.png
  Service card effect/preview.png
  Social Media Effects/preview.png
  Split Video on Page Scroll/preview.png
  Steaming cup/preview.png
  Transition Effect/preview.png
  Video-preview-button--Main/preview.png
  Water Drop Effect/preview.png
  Water Wavy Footer/preview.png
  Weild the web/preview.png
  css effects for pages/preview-convert.png
  css effects for pages/preview-line.png
  css effects for pages/preview-load2.png
  css effects for pages/preview-load3.png
  css effects for pages/preview-trirotate.png
  css effects for pages/preview-water.png
  css glowing gradient loader ring/preview.png
  demo/preview.png
  parallax effect/preview.png
  smoke effect/preview.png
Labels: DCP21, Level2

#161 modified some folder and resolving images rendering issue
  3D Animation Button/index.html
  3D Animation Button/preview.png
  smoke effect/index.html
  smoke effect/style.css
  style_links.json
Labels: DCP21, Level3

#162 Added the code for Neon Light Effect
  Neon Light Effect/index.html
  Neon Light Effect/style.css
  style_links.json
Labels: DCP21, Level2

#170 Added Animated Stacked Cards
  Animated Stacked Cards/index.html
  Animated Stacked Cards/preview.png
  Animated Stacked Cards/style.css
  style_links.json
Labels: DCP21, Level3
