Repository arpit456jain/Amazing-Css-Effects, pull requests merged in 2021-08, with the labels that each got.

#175 Added Zoom-in cards
  Zoom-in Card/index.html
  Zoom-in Card/preview.png
  Zoom-in Card/style.css
  style_links.json
Labels: DCP21, Level3

#179 animated rocket launcher
  Animated Rocket Launcher/app.js
  Animated Rocket Launcher/icon.png
  Animated Rocket Launcher/index.html
  Animated Rocket Launcher/particles.js
  Animated Rocket Launcher/preview.png
  Animated Rocket Launcher/style.css
  style_links.json
Labels: DCP21, Level2

#178 Priyakumari02 patch 1
  README.md
Labels: DCP21, Level1

#181 Card with glowing border
  Card with Glowing Border/index.html
  Card with Glowing Border/style.css
Labels: DCP21, Level2

#187 Animated realistic bubbles creates
  Animated Realistic Bubbles/index.html
  Animated Realistic Bubbles/preview.png
  Animated Realistic Bubbles/style.css
  style_links.json
Labels: DCP21, Level2

#189 Moving cursor to see comet effects
  Comets Effect/index.html
  Comets Effect/particle.js
  Comets Effect/preview.png
  Comets Effect/sketch.js
  Comets Effect/style.css
  style_links.json
Labels: DCP21, Level3

#191 Wrist Watch Effect
  Digital Wrist Watch/index.html
  Digital Wrist Watch/preview.png
  Digital Wrist Watch/style.css
  Digital Wrist Watch/watch.png
  style_links.json
Labels: Level2, DCP21

#193 Added Petals Effect
  Petals-Effect/img/bgpetal2.jpg
  Petals-Effect/img/petal.png
  Petals-Effect/index.html
  Petals-Effect/preview.PNG
  Petals-Effect/style.css
  style_links.json
Labels: Level2, DCP21

#195 making responsive for all devices
  Comets Effect/style.css
Labels: Level1, DCP21

#196 making house building
  House Building/index.html
  House Building/preview.png
  House Building/style.css
  style_links.json
Labels: Level2, DCP21

#197 rendering image solving and adding preview image
  Card with Glowing Border/preview.png
  Neon Light Effect/preview.png
  Petals-Effect/preview.PNG
  credit card payment/preview.png
  style_links.json
Labels: Level2, DCP21, urgent

#198 Making responsive for all devices
  credit card payment/style.css
Labels: Level2, DCP21
