Repository arpit456jain/Amazing-Css-Effects, pull requests merged in 2021-06, with the labels that each got.

#2 External CSS
  3d flip hover effect/3d flip hover.html
  3d flip hover effect/3d-flip-hover.css
  3d flip hover effect/index.html
  Animated Login Fom/anim-login-form.css
  Animated Login Fom/anim-login-form.html
  Animated Login Fom/animated login form.html
  Card Hover Effect/card_hover_effect.css
  Card Hover Effect/card_hover_effect.html
  Glowing Gradient Border/glow_gradient_border.css
  Glowing Gradient Border/glow_gradient_border.html
  Glowing Gradient Border/glowing gradient border.html
  Glowing loading page animation/glow_load_anim.css
  Glowing loading page animation/glow_load_page_anim.html
  Glowing loading page animation/glowing loading page animation.html
  Neon Buttons/neon light button.html
  Neon Buttons/neon_button.css
  Neon Buttons/neon_button.html
  Price Cards/price-card1.css
  Price Cards/price-card1.html
  Price Cards/price-card2.css
  Price Cards/price-card2.html
  Service card effect/service_card_effect.css
  Service card effect/service_card_effect.html
  Transition Effect/card effect.html
  Transition Effect/card_effect.css
  Transition Effect/card_effect.html
Labels: enhancement

#15 Fixed typos in Readme
  README.md
Labels: documentation, good first issue

#16 Added Templated for Issue & PR
  .github/ISSUE_TEMPLATE/Bug_Feature_Docs.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: good first issue

#17 added code of conduct
  CODE_OF_CONDUCT.md
Labels: good first issue
