Repository arpit456jain/Amazing-Css-Effects, pull requests merged in 2022-04, with the labels that each got.

#498 New Fresh UI for Website
  index.html
  script.js
  style.css
Labels: Level2, GSSoC22, ready to merge

#484 Goey footer
  Goey footer/footer.css
  Goey footer/footer.html
  style_links.json
Labels: Level2, GSSoC22

#515 Bot reconfigured
  .github/workflows/pr-labeler.yml
Labels: Level1, GSSoC22

#519 Added CSS Animation #500
  CSS Animation/index.html
  CSS Animation/style.css
Labels: Level1, GSSoC22, ready to merge

#527 Adding the link for GSSoC 2022 and The link for Video Demo and finall…
  README.md
  Thumbs.db
Labels: GSSoC22, ready to merge, Level0

#514 Add Clay Morphism Course Template Fix issue no - #479
  Animated Loaders/Style.css
  Animated Loaders/index.html
  Animated Logos/index.html
  Animated Logos/style.css
  Assasin's creed cards/index.html
  Assasin's creed cards/style.css
  Card with Glowing Border/index.html
  Card with Glowing Border/style.css
  Clay Morphism Courses/images/img1.jfif
  Clay Morphism Courses/images/img2.jpg
  Clay Morphism Courses/images/img3.jpg
  Clay Morphism Courses/images/img4.jpg
  Clay Morphism Courses/images/img5.jpg
  Clay Morphism Courses/images/profile1.jpg
  Clay Morphism Courses/index.html
  Clay Morphism Courses/styles.css
  Claymorphism hover effects/index.html
  Claymorphism hover effects/style.css
  Credit Card UI/index.html
  Credit Card UI/style.css
  Depth Effect with bg blur/depth_effect.css
  Depth Effect with bg blur/depth_effect.html
  Expanding Flex Cards/index.html
  Falling Leaves Animation/fallingleaves.css
  Falling Leaves Animation/index.html
  LED Loading Effect/index.html
  LED Loading Effect/style.css
  Rain Effect/Rain Effect.html
  Ripple Button Effect/ripple_button_effect.css
  Ripple Button Effect/ripple_button_effect.html
  Ripple Loader Animation/index.html
  Ripple Loader Animation/style.css
  Steaming cup/Tea cup.html
  Water Wavy Footer/waves_footer.css
  Water Wavy Footer/waves_footer.html
  css-glitch/app.js
  css-glitch/index.html
  css-glitch/style.scss
  snowfall_effect/index.html
  snowfall_effect/styles.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#534 Grammatical changes in ReadMe and Contributing Files .
  CONTRIBUTING.md
  README.md
Labels: GSSoC22, Level0

#533 icon-updated-successfully
  gitimages-removebg-preview.png
  index.html
  ins-removebg-preview.png
  linkedin-images-removebg-preview.png
  twitter_-removebg-preview.png
Labels: GSSoC22, Level0

#540 Fixed all broken links and added mising preview images
  Animated Countdown/preview.png
  Animated Loaders/preview.png
  Animated Logos/preview.png
  Animated Pixel Frog/preview.png
  Animated text hover/preview.png
  Animated-Glassmorphism-Vanila-Js/preview.png
  Animated-Rain-and-Lightning-effect/preview.png
  Animated_3D_Cube/preview.png
  Assasin's creed cards/preview.png
  Bulb/preview.png
  Button_to_email_effect/preview.png
  CSS Animation of planet revolving/preview.png
  Clay Morphism Courses/preview.png
  Custom Ice Cream Maker/preview.png
  Expanding Flex Cards/preview.png
  Face Hover Effect/preview.png
  Glowing socialmedia icons/preview.png
  GlowingCube/preview.png
  Goey footer/preview.png
  Highlighted Text/preview.png
  Mouse Cursor Hover/preview.png
  Neomorphic Page Loader/preview.png
  Neon Hover Navbar/preview.png
  Network Particle Animation/preview.png
  Responsive profile card/preview.png
  Site with video/preview.png
  Star Parallax/preview.png
  Submarine Animation/preview.png
  Text to life/preview.png
  Toy Girl/preview.png
  Triangular images gallery/preview.png
  animated Navigation/preview.png
  flip_card1/preview.png
  glassmorphic-flipbook/preview.png
  multi color text/preview.png
  rolling text by yash-25log/preview.png
  safari3d/preview.png
  script.js
  style.css
  style_links.json
  text effect/preview.png
Labels: Level2, GSSoC22, ready to merge

#525 Added Animated coffee maker
  Animated Coffee Maker/index.html
  Animated Coffee Maker/preview.PNG
  Animated Coffee Maker/script.js
  Animated Coffee Maker/style.css
Labels: Level2, GSSoC22

#545 Updated Readme
  README.md
Labels: Level1, GSSoC22, ready to merge

#552 Social media icons arranged
  style.css
Labels: GSSoC22, Level0

#526 Added description and proper links to Assassins Creed site
  Assasin's creed cards/index.html
  Assasin's creed cards/style.css
Labels: Level2, GSSoC22, ready to merge

#563 Add a new text animation in css
  Slashed Text Animation/imgs/Screenshot 2022-04-23 at 12.49.54 PM.png
  Slashed Text Animation/imgs/Screenshot 2022-04-23 at 12.50.01 PM.png
  Slashed Text Animation/imgs/Screenshot 2022-04-23 at 12.50.08 PM.png
  Slashed Text Animation/imgs/Screenshot 2022-04-23 at 12.50.14 PM.png
  Slashed Text Animation/imgs/Screenshot 2022-04-23 at 12.50.21 PM.png
  Slashed Text Animation/index.html
  Slashed Text Animation/styles.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#555 Added a Liquid CSS text animation.
  Animated text/index.html
  Animated text/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge
