Repository arpit456jain/Amazing-Css-Effects, pull requests merged in 2022-03, with the labels that each got.

#250 Origin/readme edit
  README.md
Labels: Level1

#252 Water Wavy Footer update
  Water Wavy Footer/waves_footer.css
  Water Wavy Footer/waves_footer.html
Labels: Level1

#271 Button to email effect
  Button_to_email_effect/index.html
  Button_to_email_effect/style.css
Labels: Level1

#278 Highlighted Text added
  Highlighted Text/index.html
  Highlighted Text/styles.css
  Neomorphic Page Loader/index.html
  Neomorphic Page Loader/styles.css
Labels: GSSoC22

#280 Added Neumorphic Contact Div ~ Pranjal Kumar
  Neumorphic Contact Div/Preview.png
  Neumorphic Contact Div/Resources/customerCare.jpg
  Neumorphic Contact Div/Resources/githubLogo.png
  Neumorphic Contact Div/Resources/linkedIn.png
  Neumorphic Contact Div/Resources/mailLogo.png
  Neumorphic Contact Div/Resources/twitterLogo.png
  Neumorphic Contact Div/Resources/whatsappLogo.png
  Neumorphic Contact Div/index.html
  Neumorphic Contact Div/style.css
Labels: GSSoC22

#304 Added Santa Claus with a snowfall background animation
  Animated Santa with snowfall bg/index.html
  Animated Santa with snowfall bg/preview.PNG
  Animated Santa with snowfall bg/styles.css
  style_links.json
Labels: Level2

#287 Added folder Sliding Checkbox
  Sliding Checkbox/index.html
  Sliding Checkbox/preview.png
  Sliding Checkbox/style.css
  style_links.json
Labels: Level1, GSSoC22

#286 fix git command
  README.md
Labels: Level1, GSSoC22

#301 added index.html style.css and script.js Fixes #issue(254)
  animated Navigation/index.html
  animated Navigation/script.js
  animated Navigation/styles.css
Labels: Level1, GSSoC22, ready to merge

#305 Added a CSS Submarine Animation
  Submarine Animation/index.html
  Submarine Animation/styles.css
  style_links.json
Labels: Level2, GSSoC22

#310 Animated_3D_cube
  Animated_3D_Cube/ANKIT.jpg
  Animated_3D_Cube/ANKIT2.jpg
  Animated_3D_Cube/ANKIT3.jpg
  Animated_3D_Cube/ANKIT4.jpg
  Animated_3D_Cube/ANKIT5.jpg
  Animated_3D_Cube/ANKIT6.jpg
  Animated_3D_Cube/Style.css
  Animated_3D_Cube/index.html
Labels: Level2, GSSoC22, ready to merge

#316 Distortion Effect Added
  Distortion Effect/index.html
  Distortion Effect/preview.png
  Distortion Effect/style.css
  style_links.json
Labels: Level1

#313 Responsive footer Added
  index.html
  logo1.png
  style.css
Labels: Level3, GSSoC22, ready to merge

#321 Custom Ice Cream Maker files added
  Custom Ice Cream Maker/index.html
  Custom Ice Cream Maker/script.js
  Custom Ice Cream Maker/styles.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#325 Added Safari 3D
  safari3d/index.html
  safari3d/style.css
Labels: Level2, GSSoC22, ready to merge

#326 Added a responsive profile card.
  Responsive profile card/index.html
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#330 interactive profile card added
  Interactive Profile Card/card_img.jpg
  Interactive Profile Card/gmail.png
  Interactive Profile Card/index.html
  Interactive Profile Card/index.js
  Interactive Profile Card/instagram.png
  Interactive Profile Card/linkedin.png
  Interactive Profile Card/preview.png
  Interactive Profile Card/style.css
  Interactive Profile Card/twitter.png
  Interactive Profile Card/whatsapp.png
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#333 Bulb
  Bulb/click.mp3
  Bulb/index.html
  Bulb/style.css
Labels: Level2

#335 update README.md
  README.md
Labels: Level0

#332 added css effects issue #308 resolved
  multi color text/index.html
  multi color text/style.css
  rolling text by yash-25log/index.html
  rolling text by yash-25log/style.css
Labels: Level2, GSSoC22

#350 Added a glassmorphic flipbook
  glassmorphic-flipbook/index.html
  glassmorphic-flipbook/style.css
Labels: Level1, GSSoC22, ready to merge

#351 Added Mouse Cursor effect
  Mouse Cursor Hover/index.html
  Mouse Cursor Hover/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#349 Animated text hover
  Animated text hover/index.html
  Animated text hover/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#354 Expanding Flex Cards
  Expanding Flex Cards/README.md
  Expanding Flex Cards/img/01.jpg
  Expanding Flex Cards/img/02.jpg
  Expanding Flex Cards/img/03.jpg
  Expanding Flex Cards/img/04.jpg
  Expanding Flex Cards/img/05.jpg
  Expanding Flex Cards/img/06.jpg
  Expanding Flex Cards/index.html
  Expanding Flex Cards/main.js
  Expanding Flex Cards/style.css
Labels: Level2

#357 Completed the issue #347 under Gssoc 22
  Animated-Rain-and-Lightning-effect/README.md
  Animated-Rain-and-Lightning-effect/background.jpg
  Animated-Rain-and-Lightning-effect/index.html
  Animated-Rain-and-Lightning-effect/rain.css
  Animated-Rain-and-Lightning-effect/rain.png
Labels: Level1, GSSoC22, ready to merge

#368 Added Glowing Cube
  GlowingCube/index.html
  GlowingCube/style.css
Labels: Level2, GSSoC22, ready to merge

#363 Glassmorphism review card
  Glassmorphism review card/images.png
  Glassmorphism review card/index.html
  Glassmorphism review card/per1.png
  Glassmorphism review card/per2.png
  Glassmorphism review card/preview.png
  Glassmorphism review card/style.css
Labels: Level1, GSSoC22, ready to merge

#344 animated button added
  3D Animation Button/index.html
  3D Animation Button/style.css
Labels: Level1, GSSoC22

#345 Added Neon Hover Navbar Folder, files. #337
  Neon Hover Navbar/index.html
  Neon Hover Navbar/style.css
Labels: Level1, GSSoC22, ready to merge

#359 Toy Girl
  Toy Girl/index.html
  Toy Girl/style.css
Labels: Level2, GSSoC22, ready to merge

#375 3D Hover Effect Added
  3D Hover Effect/Img/hover me.png
  3D Hover Effect/index.css
  3D Hover Effect/index.html
  3D Hover Effect/preview.png
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#382 Animated Heading page
  Animated Heading Page/image.png
  Animated Heading Page/index.html
  Animated Heading Page/preview.png
  Animated Heading Page/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#384 Added Animated Loader
  Animated Loaders/Style.css
  Animated Loaders/index.html
Labels: Level1, GSSoC22, ready to merge

#386 Added Star parallax
  Star Parallax/index.html
  Star Parallax/style.css
  style_links.json
Labels: Level1

#397 simple hover effect added
  Simple Hover Effect/index.html
  Simple Hover Effect/preview.png
  Simple Hover Effect/style.css
  style_links.json
Labels: Level1

#380 Colorful rain Effect Added
  Colorful Rain Effect/index.html
  Colorful Rain Effect/preview.png
  Colorful Rain Effect/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#407 Added glowing social media icons
  Glowing socialmedia icons/index.html
  Glowing socialmedia icons/style.css
  style_links.json
Labels: Level1

#416 Github link in navbar
  index.html
  style.css
Labels: Level1, GSSoC22, ready to merge

#436 Added more transition in the Assassins card
  Assasin's creed cards/index.html
  Assasin's creed cards/style.css
Labels: Level1, GSSoC22

#439 Improved Cards UI / UX
  script.js
  style.css
Labels: Level1

#446 Click and Drag
  Click and Drag/index.html
  Click and Drag/index.js
  Click and Drag/preview.png
  Click and Drag/style.css
Labels: Level2, ready to merge

#444 made the changes
  Weild the web/index.html
  Weild the web/style.css
Labels: Level1, GSSoC22, ready to merge

#440 Issue #429
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#461 Added Snowfall Effect
  snowfall_effect/index.html
  snowfall_effect/styles.css
Labels: Level1

#470 Added the Hamburger menu effect
  HamburgerMenu-Sujeet/index.html
  HamburgerMenu-Sujeet/script.js
  HamburgerMenu-Sujeet/style.css
Labels: GSSoC22, ready to merge

#457 Hover over image to see social icons with color effect #367
  hover-over-image/avatar2.png
  hover-over-image/hover.css
  hover-over-image/index.html
Labels: Level1, GSSoC22, ready to merge

#455 Animated Pixel Frog
  Animated Pixel Frog/index.html
  Animated Pixel Frog/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#468 Parallax scroll-down effect (#365)
  Parallax Scroll-Down effect/images/moon.png
  Parallax Scroll-Down effect/images/mountains_behind.png
  Parallax Scroll-Down effect/images/mountains_front.png
  Parallax Scroll-Down effect/images/stars.png
  Parallax Scroll-Down effect/index.html
  Parallax Scroll-Down effect/preview.png
  Parallax Scroll-Down effect/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#467 Added Claymorphism code files
  Claymorphism hover effects/index.html
  Claymorphism hover effects/output/Output.png
  Claymorphism hover effects/style.css
Labels: GSSoC22, ready to merge

#477 added glassmorphic navigation bar
  Glassmorphism-navbar/index.html
  Glassmorphism-navbar/preview.png
  Glassmorphism-navbar/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#485 Mentor
  README.md
Labels: Level1, GSSoC22, ready to merge

#492 Fixing Typo
  README.md
Labels: GSSoC22, ready to merge, Level0

#488 Added CSS Animation
  CSS Animation of planet revolving/Earth.jpeg
  CSS Animation of planet revolving/Mercury.jpeg
  CSS Animation of planet revolving/index.html
  CSS Animation of planet revolving/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#494 Resized the images perfectly
  README.md
Labels: GSSoC22, ready to merge
