Repository arpit456jain/Amazing-Css-Effects, pull requests merged in 2022-05, with the labels that each got.

#578 Add files via upload
  Image Accordion/IA.css
  Image Accordion/IA.html
  Image Accordion/img1.jpg
  Image Accordion/img2.jpg
  Image Accordion/img3.jpg
  Image Accordion/img4.jpg
Labels: Level2, GSSoC22, ready to merge

#576 Square-shimmer-loading-efffect
  Square-shimmer-loading-effect/Readme
  Square-shimmer-loading-effect/index.html
  Square-shimmer-loading-effect/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#602 Loading crash Animation
  Loading Effect Animation/index.html
  Loading Effect Animation/preview.gif
  Loading Effect Animation/script.js
  Loading Effect Animation/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#577 Scale-up-and-down-animation
  Scale-up-and-animation/Readme
  Scale-up-and-animation/index.html
  Scale-up-and-animation/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#610 Added Favicon
  index.html
  web_favicon.ico
Labels: GSSoC22, ready to merge, Level0

#585 3D Animaton Emoji Document
  3D_Animation_emoji/index.html
  3D_Animation_emoji/style.css
  style_links.json
Labels: Level1, GSSoC22

#618 Wave Animation
  Wave Animation/index.html
  Wave Animation/preview.gif
  Wave Animation/script.js
  Wave Animation/style.css
  style_links.json
Labels: help wanted, Level1, GSSoC22

#619 Pac Man Animation
  PacManAnimation/index.html
  PacManAnimation/preview.gif
  PacManAnimation/script.js
  PacManAnimation/style.css
Labels: help wanted, Level1, GSSoC22

#604 Added Files For #591
  Color Change Ball Drop Animation/index.html
  Color Change Ball Drop Animation/preview.gif
  Color Change Ball Drop Animation/readme.md
  Color Change Ball Drop Animation/script.js
  Color Change Ball Drop Animation/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#605 Moving Bee #592
  Moving Bee Animation/index.html
  Moving Bee Animation/preview.gif
  Moving Bee Animation/script.js
  Moving Bee Animation/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#607 Line Segment
  line Segment Animation/index.html
  line Segment Animation/preview.gif
  line Segment Animation/script.js
  line Segment Animation/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#609 Slider Time Chenge
  Time Change Slider/index.html
  Time Change Slider/preview.gif
  Time Change Slider/script.js
  Time Change Slider/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#614 Circularloadinganimation
  Circular Loading Animation/index.html
  Circular Loading Animation/preview.jpg
  Circular Loading Animation/script.js
  Circular Loading Animation/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#603 Snow man (Assign Me)
  SnowMan Animation/index.html
  SnowMan Animation/preview1.gif
  SnowMan Animation/script.js
  SnowMan Animation/style.css
  style_links.json
Labels: Level2, GSSoC22

#620 Templates not rendering #613
  Animated Search Bar/preview.png
  style_links.json
Labels: Level1, GSSoC22

#627 Smartphone Battery Performance
  Smartphone Battery Performace/index.html
  Smartphone Battery Performace/script.js
  Smartphone Battery Performace/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#634 Clip-path-animation
  Clip-path-animation/Readme.md
  Clip-path-animation/index.html
  Clip-path-animation/preview.png
  Clip-path-animation/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#678 Added vanish text effect
  Vanish Text Effect/index.html
  Vanish Text Effect/preview.png
  style_links.json
Labels: GSSoC22, ready to merge

#649 Microphone Face
  Microphone Face/index.html
  Microphone Face/preview.jpg
  Microphone Face/script.js
  Microphone Face/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#653 Add Hexagon Hover Effect
  Hexagon Hover Effect/index.html
  Hexagon Hover Effect/prev2.png
  Hexagon Hover Effect/preview.png
  Hexagon Hover Effect/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#655 Added LetterAnimation
  LetterAnimation/README.md
  LetterAnimation/index.html
  LetterAnimation/script.js
  LetterAnimation/style.css
  LetterAnimation/style_link.json
Labels: GSSoC22, ready to merge

#679 Wavy Text Animation
  Wavy Text Animation/Preview.png
  Wavy Text Animation/index.html
  Wavy Text Animation/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#636 Breathe Animation
  Breathe Animation/index.html
  Breathe Animation/preview.png
  Breathe Animation/script.js
  Breathe Animation/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#652 Illuminati Animated
  Illuminati Pyramid Animation/index.html
  Illuminati Pyramid Animation/preview.jpg
  Illuminati Pyramid Animation/script.js
  Illuminati Pyramid Animation/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#682 Day Night Toggle
  Day Night Toggle/index.html
  Day Night Toggle/preview1.png
  Day Night Toggle/preview2.png
  Day Night Toggle/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#683 Adding Heart-trail-animation!
  Heart-trail-animation/index.html
  Heart-trail-animation/index.js
  Heart-trail-animation/png/Screenshot 2022-05-17 at 6.41.47 PM.png
  Heart-trail-animation/style.css
  Heart-trail-animation/style_links.json
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#685 Enhanced the UI of Animated Heading Page
  Animated Heading Page/style.css
Labels: Level1, GSSoC22, ready to merge

#690 Fixed responsiveness for Petals-Effect
  Petals-Effect/style.css
Labels: Level1, GSSoC22, ready to merge

#696 Multi-coloured Animated Text files added
  Multi-coloured Animated Text/index.html
  Multi-coloured Animated Text/preview.png
  Multi-coloured Animated Text/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#697 Modified Animated logos
  Animated Logos/index.html
  Animated Logos/preview.png
  Animated Logos/style.css
Labels: Level1, GSSoC22, ready to merge

#703 Mayank del/issue693
  style_links.json
  svg-volleyball-player-animation-effect/index.html
  svg-volleyball-player-animation-effect/style.css
Labels: Level2, GSSoC22, ready to merge

#704 Added Animated Carousel Template
  Animated Carousel/index.css
  Animated Carousel/index.html
  Animated Carousel/preview.png
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#705 #698 Css penguin animation
  CSS_Penguin_Art/index.html
  CSS_Penguin_Art/preview.png
  CSS_Penguin_Art/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#689 PR for Carousel Effect
  Carousel Effect/1101027.jpg
  Carousel Effect/1579508.jpg
  Carousel Effect/1579511.jpg
  Carousel Effect/327654.jpg
  Carousel Effect/902870.jpg
  Carousel Effect/index.html
  style_links.json
Labels: GSSoC22, ready to merge, Level0

#710 added elegant-notepad-card
  Elegant-Notepad-Card/images/notes1.jpg
  Elegant-Notepad-Card/index.html
  Elegant-Notepad-Card/mobile.css
  Elegant-Notepad-Card/preview.png
  Elegant-Notepad-Card/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#709 Fixed Bug - Refactored Images. Website enhanced
  Animated UI Design/index.html
  Expanding Flex Cards/index.html
  Profile Card/index.html
  Social Media Effects/index.html
  hover-over-image/index.html
  logo.png
  script.js
Labels: GSSoC22, ready to merge

#721 Social Media Icon Hover Effect Added
  Social Media Icon Hover/index.html
  Social Media Icon Hover/preview.png
  Social Media Icon Hover/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#720 Added content to Rotating card
  Rotating cards/index.html
  Rotating cards/preview.png
  Rotating cards/style.css
Labels: GSSoC22, ready to merge

#713 Background Animation of Gift Falling
  Background Animation of Gifts Falling/images/b1.png
  Background Animation of Gifts Falling/images/b2.png
  Background Animation of Gifts Falling/images/b3.png
  Background Animation of Gifts Falling/images/dollar.png
  Background Animation of Gifts Falling/images/ip.png
  Background Animation of Gifts Falling/images/mac1.png
  Background Animation of Gifts Falling/images/mac2.png
  Background Animation of Gifts Falling/index.html
  Background Animation of Gifts Falling/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#695 Codepen-button-animation
  Codepen-button-animaiton/Readme.md
  Codepen-button-animaiton/index.html
  Codepen-button-animaiton/preview.png
  Codepen-button-animaiton/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#730 Twinkling star CSS effect reference links
  README_TwinklingStarsCSSeffect.md
  TwinklingStar_CSSeffect/images/planet-removebg-preview.png
  TwinklingStar_CSSeffect/index.html
  TwinklingStar_CSSeffect/preview.png
  TwinklingStar_CSSeffect/style.css
Labels: GSSoC22

#732 Circular Progress Bar
  Circular Progress Bar/index.html
  Circular Progress Bar/preview.png
  Circular Progress Bar/style.css
Labels: GSSoC22

#734 Deleted Plagrised Projects from the repository
  Bulb/click.mp3
  Bulb/index.html
  Bulb/preview.png
  Bulb/style.css
  Colorful Rain Effect/index.html
  Colorful Rain Effect/preview.png
  Colorful Rain Effect/style.css
  Custom Ice Cream Maker/index.html
  Custom Ice Cream Maker/preview.png
  Custom Ice Cream Maker/script.js
  Custom Ice Cream Maker/styles.css
  Submarine Animation/index.html
  Submarine Animation/preview.png
  Submarine Animation/styles.css
  safari3d/index.html
  safari3d/preview.png
  safari3d/style.css
  snowfall Effect/index.html
  snowfall Effect/preview.png
  snowfall Effect/styles.css
Labels: GSSoC22
